package com.training.r.model;

import java.util.ArrayList;
import java.util.List;

public class DichVuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public DichVuExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMadvIsNull() {
            addCriterion("MaDV is null");
            return (Criteria) this;
        }

        public Criteria andMadvIsNotNull() {
            addCriterion("MaDV is not null");
            return (Criteria) this;
        }

        public Criteria andMadvEqualTo(String value) {
            addCriterion("MaDV =", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvNotEqualTo(String value) {
            addCriterion("MaDV <>", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvGreaterThan(String value) {
            addCriterion("MaDV >", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvGreaterThanOrEqualTo(String value) {
            addCriterion("MaDV >=", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvLessThan(String value) {
            addCriterion("MaDV <", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvLessThanOrEqualTo(String value) {
            addCriterion("MaDV <=", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvLike(String value) {
            addCriterion("MaDV like", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvNotLike(String value) {
            addCriterion("MaDV not like", value, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvIn(List<String> values) {
            addCriterion("MaDV in", values, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvNotIn(List<String> values) {
            addCriterion("MaDV not in", values, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvBetween(String value1, String value2) {
            addCriterion("MaDV between", value1, value2, "madv");
            return (Criteria) this;
        }

        public Criteria andMadvNotBetween(String value1, String value2) {
            addCriterion("MaDV not between", value1, value2, "madv");
            return (Criteria) this;
        }

        public Criteria andDongiaIsNull() {
            addCriterion("DonGia is null");
            return (Criteria) this;
        }

        public Criteria andDongiaIsNotNull() {
            addCriterion("DonGia is not null");
            return (Criteria) this;
        }

        public Criteria andDongiaEqualTo(Integer value) {
            addCriterion("DonGia =", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaNotEqualTo(Integer value) {
            addCriterion("DonGia <>", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaGreaterThan(Integer value) {
            addCriterion("DonGia >", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaGreaterThanOrEqualTo(Integer value) {
            addCriterion("DonGia >=", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaLessThan(Integer value) {
            addCriterion("DonGia <", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaLessThanOrEqualTo(Integer value) {
            addCriterion("DonGia <=", value, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaIn(List<Integer> values) {
            addCriterion("DonGia in", values, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaNotIn(List<Integer> values) {
            addCriterion("DonGia not in", values, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaBetween(Integer value1, Integer value2) {
            addCriterion("DonGia between", value1, value2, "dongia");
            return (Criteria) this;
        }

        public Criteria andDongiaNotBetween(Integer value1, Integer value2) {
            addCriterion("DonGia not between", value1, value2, "dongia");
            return (Criteria) this;
        }

        public Criteria andDonvitinhIsNull() {
            addCriterion("DonViTinh is null");
            return (Criteria) this;
        }

        public Criteria andDonvitinhIsNotNull() {
            addCriterion("DonViTinh is not null");
            return (Criteria) this;
        }

        public Criteria andDonvitinhEqualTo(String value) {
            addCriterion("DonViTinh =", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhNotEqualTo(String value) {
            addCriterion("DonViTinh <>", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhGreaterThan(String value) {
            addCriterion("DonViTinh >", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhGreaterThanOrEqualTo(String value) {
            addCriterion("DonViTinh >=", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhLessThan(String value) {
            addCriterion("DonViTinh <", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhLessThanOrEqualTo(String value) {
            addCriterion("DonViTinh <=", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhLike(String value) {
            addCriterion("DonViTinh like", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhNotLike(String value) {
            addCriterion("DonViTinh not like", value, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhIn(List<String> values) {
            addCriterion("DonViTinh in", values, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhNotIn(List<String> values) {
            addCriterion("DonViTinh not in", values, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhBetween(String value1, String value2) {
            addCriterion("DonViTinh between", value1, value2, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andDonvitinhNotBetween(String value1, String value2) {
            addCriterion("DonViTinh not between", value1, value2, "donvitinh");
            return (Criteria) this;
        }

        public Criteria andTendvIsNull() {
            addCriterion("TenDV is null");
            return (Criteria) this;
        }

        public Criteria andTendvIsNotNull() {
            addCriterion("TenDV is not null");
            return (Criteria) this;
        }

        public Criteria andTendvEqualTo(String value) {
            addCriterion("TenDV =", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvNotEqualTo(String value) {
            addCriterion("TenDV <>", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvGreaterThan(String value) {
            addCriterion("TenDV >", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvGreaterThanOrEqualTo(String value) {
            addCriterion("TenDV >=", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvLessThan(String value) {
            addCriterion("TenDV <", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvLessThanOrEqualTo(String value) {
            addCriterion("TenDV <=", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvLike(String value) {
            addCriterion("TenDV like", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvNotLike(String value) {
            addCriterion("TenDV not like", value, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvIn(List<String> values) {
            addCriterion("TenDV in", values, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvNotIn(List<String> values) {
            addCriterion("TenDV not in", values, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvBetween(String value1, String value2) {
            addCriterion("TenDV between", value1, value2, "tendv");
            return (Criteria) this;
        }

        public Criteria andTendvNotBetween(String value1, String value2) {
            addCriterion("TenDV not between", value1, value2, "tendv");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DICHVU
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 02 14:52:42 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}