package com.training.r.model;

public class DichVu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICHVU.MaDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String madv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICHVU.DonGia
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private Integer dongia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICHVU.DonViTinh
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String donvitinh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICHVU.TenDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String tendv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICHVU.MaDV
     *
     * @return the value of DICHVU.MaDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getMadv() {
        return madv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICHVU.MaDV
     *
     * @param madv the value for DICHVU.MaDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setMadv(String madv) {
        this.madv = madv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICHVU.DonGia
     *
     * @return the value of DICHVU.DonGia
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public Integer getDongia() {
        return dongia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICHVU.DonGia
     *
     * @param dongia the value for DICHVU.DonGia
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setDongia(Integer dongia) {
        this.dongia = dongia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICHVU.DonViTinh
     *
     * @return the value of DICHVU.DonViTinh
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getDonvitinh() {
        return donvitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICHVU.DonViTinh
     *
     * @param donvitinh the value for DICHVU.DonViTinh
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setDonvitinh(String donvitinh) {
        this.donvitinh = donvitinh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICHVU.TenDV
     *
     * @return the value of DICHVU.TenDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getTendv() {
        return tendv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICHVU.TenDV
     *
     * @param tendv the value for DICHVU.TenDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setTendv(String tendv) {
        this.tendv = tendv;
    }
}