package com.training.r.model;

public class KhachHang {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KHACHHANG.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String makh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KHACHHANG.DiaChi
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String diachi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KHACHHANG.DiaChiEmail
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String diachiemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KHACHHANG.SoDienThoai
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String sodienthoai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KHACHHANG.TenKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String tenkh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KHACHHANG.MaKH
     *
     * @return the value of KHACHHANG.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getMakh() {
        return makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KHACHHANG.MaKH
     *
     * @param makh the value for KHACHHANG.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setMakh(String makh) {
        this.makh = makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KHACHHANG.DiaChi
     *
     * @return the value of KHACHHANG.DiaChi
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KHACHHANG.DiaChi
     *
     * @param diachi the value for KHACHHANG.DiaChi
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KHACHHANG.DiaChiEmail
     *
     * @return the value of KHACHHANG.DiaChiEmail
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getDiachiemail() {
        return diachiemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KHACHHANG.DiaChiEmail
     *
     * @param diachiemail the value for KHACHHANG.DiaChiEmail
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setDiachiemail(String diachiemail) {
        this.diachiemail = diachiemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KHACHHANG.SoDienThoai
     *
     * @return the value of KHACHHANG.SoDienThoai
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getSodienthoai() {
        return sodienthoai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KHACHHANG.SoDienThoai
     *
     * @param sodienthoai the value for KHACHHANG.SoDienThoai
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setSodienthoai(String sodienthoai) {
        this.sodienthoai = sodienthoai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KHACHHANG.TenKH
     *
     * @return the value of KHACHHANG.TenKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getTenkh() {
        return tenkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KHACHHANG.TenKH
     *
     * @param tenkh the value for KHACHHANG.TenKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setTenkh(String tenkh) {
        this.tenkh = tenkh;
    }
}