package com.training.r.model;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class May {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MAY.MaMay
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	
	@NotNull(message = "Thiếu username")
	@NotEmpty(message = "Thiếu username")
	@Size(min = 1, message = "Vui long nhap")
	private String mamay;
	
	@NotNull(message = "Thiếu username")
	@NotEmpty(message = "Thiếu username")
	@Size(min = 1, message = "Vui long nhap")
	private String trangthai;
	
	@NotNull(message = "Thiếu username")
	@NotEmpty(message = "Thiếu username")
	@Size(min = 1, message = "Vui long nhap")
	private String vitri;

	
	public String getMamay() {
		return mamay;
	}

	public void setMamay(String mamay) {
		this.mamay = mamay;
	}

	public String getTrangthai() {
		return trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	public String getVitri() {
		return vitri;
	}

	public void setVitri(String vitri) {
		this.vitri = vitri;
	}
}