package com.training.r.model;

public class SuDungMay extends SuDungMayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGMAY.ThoiGian
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String thoigian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGMAY.ThoiGian
     *
     * @return the value of SUDUNGMAY.ThoiGian
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getThoigian() {
        return thoigian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGMAY.ThoiGian
     *
     * @param thoigian the value for SUDUNGMAY.ThoiGian
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setThoigian(String thoigian) {
        this.thoigian = thoigian;
    }
}