package com.training.r.model;

public class SuDungDichVu extends SuDungDichVuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGDICHVU.SoLuong
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private Integer soluong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGDICHVU.SoLuong
     *
     * @return the value of SUDUNGDICHVU.SoLuong
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public Integer getSoluong() {
        return soluong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGDICHVU.SoLuong
     *
     * @param soluong the value for SUDUNGDICHVU.SoLuong
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
}