package com.training.r.model;

public class SuDungDichVuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGDICHVU.MaDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String madv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGDICHVU.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String makh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGDICHVU.NgaySuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String ngaysudung;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGDICHVU.GioSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String giosudung;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGDICHVU.MaDV
     *
     * @return the value of SUDUNGDICHVU.MaDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getMadv() {
        return madv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGDICHVU.MaDV
     *
     * @param madv the value for SUDUNGDICHVU.MaDV
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setMadv(String madv) {
        this.madv = madv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGDICHVU.MaKH
     *
     * @return the value of SUDUNGDICHVU.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getMakh() {
        return makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGDICHVU.MaKH
     *
     * @param makh the value for SUDUNGDICHVU.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setMakh(String makh) {
        this.makh = makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGDICHVU.NgaySuDung
     *
     * @return the value of SUDUNGDICHVU.NgaySuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getNgaysudung() {
        return ngaysudung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGDICHVU.NgaySuDung
     *
     * @param ngaysudung the value for SUDUNGDICHVU.NgaySuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setNgaysudung(String ngaysudung) {
        this.ngaysudung = ngaysudung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGDICHVU.GioSuDung
     *
     * @return the value of SUDUNGDICHVU.GioSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getGiosudung() {
        return giosudung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGDICHVU.GioSuDung
     *
     * @param giosudung the value for SUDUNGDICHVU.GioSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setGiosudung(String giosudung) {
        this.giosudung = giosudung;
    }

	public SuDungDichVuKey(String madv, String makh, String ngaysudung, String giosudung) {
		super();
		this.madv = madv;
		this.makh = makh;
		this.ngaysudung = ngaysudung;
		this.giosudung = giosudung;
	}

	public SuDungDichVuKey() {
		super();
	}
    
    
}