package com.training.r.model;

import java.util.ArrayList;
import java.util.List;

public class SuDungMayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public SuDungMayExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMakhIsNull() {
            addCriterion("MaKH is null");
            return (Criteria) this;
        }

        public Criteria andMakhIsNotNull() {
            addCriterion("MaKH is not null");
            return (Criteria) this;
        }

        public Criteria andMakhEqualTo(String value) {
            addCriterion("MaKH =", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotEqualTo(String value) {
            addCriterion("MaKH <>", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhGreaterThan(String value) {
            addCriterion("MaKH >", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhGreaterThanOrEqualTo(String value) {
            addCriterion("MaKH >=", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhLessThan(String value) {
            addCriterion("MaKH <", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhLessThanOrEqualTo(String value) {
            addCriterion("MaKH <=", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhLike(String value) {
            addCriterion("MaKH like", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotLike(String value) {
            addCriterion("MaKH not like", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhIn(List<String> values) {
            addCriterion("MaKH in", values, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotIn(List<String> values) {
            addCriterion("MaKH not in", values, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhBetween(String value1, String value2) {
            addCriterion("MaKH between", value1, value2, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotBetween(String value1, String value2) {
            addCriterion("MaKH not between", value1, value2, "makh");
            return (Criteria) this;
        }

        public Criteria andMamayIsNull() {
            addCriterion("MaMay is null");
            return (Criteria) this;
        }

        public Criteria andMamayIsNotNull() {
            addCriterion("MaMay is not null");
            return (Criteria) this;
        }

        public Criteria andMamayEqualTo(String value) {
            addCriterion("MaMay =", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayNotEqualTo(String value) {
            addCriterion("MaMay <>", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayGreaterThan(String value) {
            addCriterion("MaMay >", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayGreaterThanOrEqualTo(String value) {
            addCriterion("MaMay >=", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayLessThan(String value) {
            addCriterion("MaMay <", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayLessThanOrEqualTo(String value) {
            addCriterion("MaMay <=", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayLike(String value) {
            addCriterion("MaMay like", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayNotLike(String value) {
            addCriterion("MaMay not like", value, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayIn(List<String> values) {
            addCriterion("MaMay in", values, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayNotIn(List<String> values) {
            addCriterion("MaMay not in", values, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayBetween(String value1, String value2) {
            addCriterion("MaMay between", value1, value2, "mamay");
            return (Criteria) this;
        }

        public Criteria andMamayNotBetween(String value1, String value2) {
            addCriterion("MaMay not between", value1, value2, "mamay");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungIsNull() {
            addCriterion("NgayBatDauSuDung is null");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungIsNotNull() {
            addCriterion("NgayBatDauSuDung is not null");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungEqualTo(String value) {
            addCriterion("NgayBatDauSuDung =", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungNotEqualTo(String value) {
            addCriterion("NgayBatDauSuDung <>", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungGreaterThan(String value) {
            addCriterion("NgayBatDauSuDung >", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungGreaterThanOrEqualTo(String value) {
            addCriterion("NgayBatDauSuDung >=", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungLessThan(String value) {
            addCriterion("NgayBatDauSuDung <", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungLessThanOrEqualTo(String value) {
            addCriterion("NgayBatDauSuDung <=", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungLike(String value) {
            addCriterion("NgayBatDauSuDung like", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungNotLike(String value) {
            addCriterion("NgayBatDauSuDung not like", value, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungIn(List<String> values) {
            addCriterion("NgayBatDauSuDung in", values, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungNotIn(List<String> values) {
            addCriterion("NgayBatDauSuDung not in", values, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungBetween(String value1, String value2) {
            addCriterion("NgayBatDauSuDung between", value1, value2, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andNgaybatdausudungNotBetween(String value1, String value2) {
            addCriterion("NgayBatDauSuDung not between", value1, value2, "ngaybatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungIsNull() {
            addCriterion("GioBatDauSuDung is null");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungIsNotNull() {
            addCriterion("GioBatDauSuDung is not null");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungEqualTo(String value) {
            addCriterion("GioBatDauSuDung =", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungNotEqualTo(String value) {
            addCriterion("GioBatDauSuDung <>", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungGreaterThan(String value) {
            addCriterion("GioBatDauSuDung >", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungGreaterThanOrEqualTo(String value) {
            addCriterion("GioBatDauSuDung >=", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungLessThan(String value) {
            addCriterion("GioBatDauSuDung <", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungLessThanOrEqualTo(String value) {
            addCriterion("GioBatDauSuDung <=", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungLike(String value) {
            addCriterion("GioBatDauSuDung like", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungNotLike(String value) {
            addCriterion("GioBatDauSuDung not like", value, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungIn(List<String> values) {
            addCriterion("GioBatDauSuDung in", values, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungNotIn(List<String> values) {
            addCriterion("GioBatDauSuDung not in", values, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungBetween(String value1, String value2) {
            addCriterion("GioBatDauSuDung between", value1, value2, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andGiobatdausudungNotBetween(String value1, String value2) {
            addCriterion("GioBatDauSuDung not between", value1, value2, "giobatdausudung");
            return (Criteria) this;
        }

        public Criteria andThoigianIsNull() {
            addCriterion("ThoiGian is null");
            return (Criteria) this;
        }

        public Criteria andThoigianIsNotNull() {
            addCriterion("ThoiGian is not null");
            return (Criteria) this;
        }

        public Criteria andThoigianEqualTo(String value) {
            addCriterion("ThoiGian =", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianNotEqualTo(String value) {
            addCriterion("ThoiGian <>", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianGreaterThan(String value) {
            addCriterion("ThoiGian >", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianGreaterThanOrEqualTo(String value) {
            addCriterion("ThoiGian >=", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianLessThan(String value) {
            addCriterion("ThoiGian <", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianLessThanOrEqualTo(String value) {
            addCriterion("ThoiGian <=", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianLike(String value) {
            addCriterion("ThoiGian like", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianNotLike(String value) {
            addCriterion("ThoiGian not like", value, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianIn(List<String> values) {
            addCriterion("ThoiGian in", values, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianNotIn(List<String> values) {
            addCriterion("ThoiGian not in", values, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianBetween(String value1, String value2) {
            addCriterion("ThoiGian between", value1, value2, "thoigian");
            return (Criteria) this;
        }

        public Criteria andThoigianNotBetween(String value1, String value2) {
            addCriterion("ThoiGian not between", value1, value2, "thoigian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 02 14:52:42 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}