package com.training.r.model;

public class SuDungMayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGMAY.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String makh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGMAY.MaMay
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String mamay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGMAY.NgayBatDauSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String ngaybatdausudung;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUDUNGMAY.GioBatDauSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    private String giobatdausudung;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGMAY.MaKH
     *
     * @return the value of SUDUNGMAY.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getMakh() {
        return makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGMAY.MaKH
     *
     * @param makh the value for SUDUNGMAY.MaKH
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setMakh(String makh) {
        this.makh = makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGMAY.MaMay
     *
     * @return the value of SUDUNGMAY.MaMay
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getMamay() {
        return mamay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGMAY.MaMay
     *
     * @param mamay the value for SUDUNGMAY.MaMay
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setMamay(String mamay) {
        this.mamay = mamay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGMAY.NgayBatDauSuDung
     *
     * @return the value of SUDUNGMAY.NgayBatDauSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getNgaybatdausudung() {
        return ngaybatdausudung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGMAY.NgayBatDauSuDung
     *
     * @param ngaybatdausudung the value for SUDUNGMAY.NgayBatDauSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setNgaybatdausudung(String ngaybatdausudung) {
        this.ngaybatdausudung = ngaybatdausudung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUDUNGMAY.GioBatDauSuDung
     *
     * @return the value of SUDUNGMAY.GioBatDauSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public String getGiobatdausudung() {
        return giobatdausudung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUDUNGMAY.GioBatDauSuDung
     *
     * @param giobatdausudung the value for SUDUNGMAY.GioBatDauSuDung
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    public void setGiobatdausudung(String giobatdausudung) {
        this.giobatdausudung = giobatdausudung;
    }

	public SuDungMayKey(String makh, String mamay, String ngaybatdausudung, String giobatdausudung) {
		super();
		this.makh = makh;
		this.mamay = mamay;
		this.ngaybatdausudung = ngaybatdausudung;
		this.giobatdausudung = giobatdausudung;
	}

	public SuDungMayKey() {
		super();
	}
    
}