package com.training.r.mapper;

import com.training.r.model.DichVu;
import com.training.r.model.DichVuExample;
import com.training.r.model.KhachHang;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DichVuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    long countByExample(DichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByExample(DichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByPrimaryKey(String madv);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insert(DichVu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insertSelective(DichVu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    List<DichVu> selectByExample(DichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    DichVu selectByPrimaryKey(String madv);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExampleSelective(@Param("row") DichVu row, @Param("example") DichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExample(@Param("row") DichVu row, @Param("example") DichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKeySelective(DichVu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKey(DichVu row);
    
    
    List<DichVu> selectByKeyword (String keyWord);
}