package com.training.r.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.training.r.model.KhachHang;
import com.training.r.model.KhachHangExample;

@Mapper
public interface KhachHangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    long countByExample(KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByExample(KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByPrimaryKey(String makh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insert(KhachHang row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insertSelective(KhachHang row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    List<KhachHang> selectByExample(KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    KhachHang selectByPrimaryKey(String makh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExampleSelective(@Param("row") KhachHang row, @Param("example") KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExample(@Param("row") KhachHang row, @Param("example") KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKeySelective(KhachHang row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KHACHHANG
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKey(KhachHang row);
    
    
    List<KhachHang> selectByKeyword (String keyWord);
    
}