package com.training.r.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.training.r.model.May;
import com.training.r.model.MayExample;


@Mapper
public interface MayMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	long countByExample(MayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int deleteByExample(MayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int deleteByPrimaryKey(String mamay);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int insert(May row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int insertSelective(May row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	List<May> selectByExample(MayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	May selectByPrimaryKey(String mamay);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") May row, @Param("example") MayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int updateByExample(@Param("row") May row, @Param("example") MayExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int updateByPrimaryKeySelective(May row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MAY
	 * @mbg.generated  Thu Mar 02 14:52:42 ICT 2023
	 */
	int updateByPrimaryKey(May row);

	List<May> selectByKeyword(String keyWord);
}