package com.training.r.mapper;

import com.training.r.model.May;
import com.training.r.model.SuDungMay;
import com.training.r.model.SuDungMayExample;
import com.training.r.model.SuDungMayKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SuDungMayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    long countByExample(SuDungMayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByExample(SuDungMayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByPrimaryKey(SuDungMayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insert(SuDungMay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insertSelective(SuDungMay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    List<SuDungMay> selectByExample(SuDungMayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    SuDungMay selectByPrimaryKey(SuDungMayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExampleSelective(@Param("row") SuDungMay row, @Param("example") SuDungMayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExample(@Param("row") SuDungMay row, @Param("example") SuDungMayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKeySelective(SuDungMay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGMAY
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKey(SuDungMay row);
    
    List<SuDungMay> selectByKeyword(String keyWord);
}