package com.training.r.mapper;

import com.training.r.model.SuDungDichVu;
import com.training.r.model.SuDungDichVuExample;
import com.training.r.model.SuDungDichVuKey;
import com.training.r.model.SuDungMay;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SuDungDichVuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    long countByExample(SuDungDichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByExample(SuDungDichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int deleteByPrimaryKey(SuDungDichVuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insert(SuDungDichVu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int insertSelective(SuDungDichVu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    List<SuDungDichVu> selectByExample(SuDungDichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    SuDungDichVu selectByPrimaryKey(SuDungDichVuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExampleSelective(@Param("row") SuDungDichVu row, @Param("example") SuDungDichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByExample(@Param("row") SuDungDichVu row, @Param("example") SuDungDichVuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKeySelective(SuDungDichVu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUDUNGDICHVU
     *
     * @mbg.generated Thu Mar 02 14:52:42 ICT 2023
     */
    int updateByPrimaryKey(SuDungDichVu row);
    
    List<SuDungDichVu> selectByKeyword(String keyWord);
    
}